# Generated by Django 3.0.3 on 2020-03-01 23:01

from django.db import migrations, models
import django.db.models.deletion
import petshop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'FEMALE'), (2, 'MALE')], default=petshop.models.Sex['UNKNOWN'])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.Owner')),
            ],
        ),
    ]
